AgendueWeb/config/routes.rb
Agendue::Application.routes.draw do

  resources :notifications

  get "agendue_calendar/show"
  get "agendue_calendar/ics"
  resources :personal_tasks
  get 'personal_tasks/all/complete' => 'personal_tasks#complete'
  get 'personal_tasks/all/incomplete' => 'personal_tasks#incomplete'

  resources :premium_users

  resources :devices

  resources :helps

    root 'home#home'

  get "password_resets/new"
  get 'index' => 'static#home'
  get 'users/new' =>'users#new'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get 'projects/:id/empty_wiki' => 'projects#empty_wiki'
  post 'projects/:id/removeshare' => 'projects#removeshare', as: :removeshare
  get 'projects/:id/messages' => 'projects#allmessages', as: :project_messages
  get 'projects/:id/public' => 'projects#show_public', as: :project_show_public
  get '/projects/shares' => 'projects#shares', as: :projects_shares_OLD
  get 'projects/:id/shares' => 'projects#shares', as: :project_shares
  get '/tasks/assigned' => 'tasks#assigned', as: :your_tasks
  get '/tasks/calendar' => 'agendue_calendar#show_old', as: :old_calendar
  get '/calendar' => 'agendue_calendar#show', as: :tasks_calendar
  get '/home' => 'static#home'
  get '/contact' => 'static#contact'
  get '/about' => 'static#about'
  get '/privacy' => 'static#privacy'
  get '/termsandconditions' =>'static#termsandconditions'

  get 'admin' => 'admin#index'
  get 'landing' => 'landing#index'
  get 'landing/score' => 'landing#score'
  get 'landing/personal' => 'landing#personal'
  get 'landing/incomplete_count' => 'landing#incomplete_count'
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get]
  match '/auth/failure', :to => 'sessions#failure', via: [:get]

  get 'userinfo' => 'users#show'
  get '/user' => 'users#show', as: :just_user
  get 'projects/copy' => 'projects#copy_start', as: :copystart
  get 'projects/:id/copy' => 'projects#copy_options', as: :copyname
  post 'projects/:id/copy' => 'projects#copy_run', as: :copy
  post 'messages' => 'messages#create', as: :messages
  get 'projects/:id/wiki' => 'projects#showwiki', as: :show_wiki
  get 'projects/:id/wiki/edit' => 'projects#editwiki', as: :edit_project_wiki
  post 'projects/:id/wiki/edit' => 'projects#updateprojectwiki', as: :project_wiki
  get 'projects/:id/tasks/complete' => 'projects#complete_tasks', as: :project_complete_tasks
  get 'projects/:id/tasks/incomplete' => 'projects#incomplete_tasks', as: :project_incomplete_tasks
  get 'projects/:id/tasks' => 'projects#tasks', as: :project_tasks
  get 'projects/:id/shares/canshare' => 'projects#canshare', as: :project_can_share
  get 'projects/:id/shares' => 'projects#shares'
  get 'oauthpassword' => 'sessions#oauthpassword', as: :oauthpassword
  get 'tour' => 'newusertour#tour', as: :tour
  get 'help' => 'helps#index', as: :all_help
  get 'tasks/assigned/complete' => 'tasks#assignedcomplete', as: :complete_assigned_tasks
  get 'tasks/assigned/incomplete' => 'tasks#assignedincomplete', as: :incomplete_assigned_tasks
  get 'tasks/complete' => 'tasks#allcomplete', as: :complete_tasks
  get 'tasks/incomplete' => 'tasks#allincomplete', as: :incomplete_tasks
  get 'tasks/labels' => 'tasks#labels', as: :task_labels
  get 'calendar/feed/:id/:hash' => 'agendue_calendar#ics', as: :calendar_ics
  get 'admin/addpremium' => 'admin#createpremiumoverride', as: :create_premium_override
  post 'admin/addpremium' => 'admin#addpremiumoverride', as: :add_premium_override
  get 'admin/showpremium' => 'admin#showpremiumoverride', as: :show_premium_override
  get 'charges/explainfeatures' => 'charges#explainfeatures', as: :explainfeatures
  get 'atlanta' => 'static#atlanta', as: :atlanta
  get 'acknowledgements' => 'static#acknowledgements', as: :acknowledgements

  #analytics
  get 'projects/:id/analytics' => 'analytics#index', as: :project_analytics
  get 'projects/:id/analytics/status' => 'analytics#status', as: :analytics_status
  get 'projects/:id/analytics/tasks_per_user' => 'analytics#tasks_per_user', as: :analytics_tasks_per_user
  get 'projects/:id/analytics/tasks_complete_per_user' => 'analytics#tasks_complete_per_user', as: :analytics_tasks_complete_per_user
  get 'projects/:id/analytics/percent_complete' => 'analytics#percent_complete', as: :analytics_percent_complete

  resources :admin

  resources :help

  resources :charges

  resources :users

  resources :tasks

  resources :projects

  resources :sessions

  resources :password_resets
end

AgendueWeb/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def home
		if User.find_by_id(session[:userid]) != nil 
	  		@loggedin = true
	  		redirect_to landing_path
	  	else
	  		@loggedin = false
	  		respond_to do |format|
	  			format.html
	  			format.mobile
	  		end
	  	end
	end
end

AgendueWeb/app/helpers/home_helper.rb
module HomeHelper
end

AgendueWeb/app/views/home/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Agendue</title>
   <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-49704891-1', 'agendue.com');
    ga('send', 'pageview');

  </script>
  <link href='https://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <link rel="apple-touch-icon" href="assets/agendue-icon.png" >
</head>
<body class="homepage">
  <nav class="navbar navbar-default home" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("agendue-icon.png", :alt => "Agendue", :class => "nav-icon"), root_path, :class => "navbar-brand" %>
        <%= link_to "Agendue", root_path, :class => "navbar-brand home" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right home">
            <li><%= link_to "Sign Up", new_user_path %></li>
            <li><%= link_to "Sign In", login_path %></li>

        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <div class="home-container">
    <div class="jumbotron home home-top">
      <h1>Organize all your projects with <span class="orange">Agendue</span></h1>
      <div class="col-md-9"></div>
      <div class="col-md-3">
        <%= link_to "Sign In", login_path, :class => "btn btn-ghost btn-lg btn-sign-up orange-hover" %>
        <%= link_to "Sign Up", new_user_path, :class => "btn btn-ghost btn-lg btn-sign-up orange-hover" %>
      </div>
    </div>
    <div class="jumbotron home home-agendue-is">
      <div class="row">
        <div class="col-md-3">
          <h1><span class="orange">Agendue</span> is: </h1>
        </div>
        <div class="col-md-2"><h1>fast</h1></div>
      </div>
      <div class="row">
        <div class="col-md-3 visible-md-block visible-lg-block"></div>
        <div class="col-md-2"><h1>easy</h1></div>
      </div>
      <div class="row">
        <div class="col-md-3 visible-md-block visible-lg-block"></div>
        <div class="col-md-2"><h1>simple</h1></div>
      </div>
      <div class="row">
        <div class="col-md-3 visible-md-block visible-lg-block"></div>
        <div class="col-md-2"><h1>organized</h1></div>
      </div>
    </div>
    <div class="jumbotron home home-devices">
      <h1><span class="orange">Agendue</span> is on your favorite devices.</h1>
      <div class="row text-center visible-sm-block visible-md-block visible-lg-block">
        <%= image_tag("home/Web-Agendue.png", :alt => "Agendue Web", :class =>"img-responsive inline home-device") %>
        <%= image_tag("home/iPhone-Agendue.png", :alt => "Agendue iOS", :class =>"img-responsive inline home-device") %>
        <%= image_tag("home/Android-Agendue.png", :alt => "Agendue Android", :class => "img-responsive inline home-device") %>
      </div>
      <div class="row text-center">
        <a href="https://itunes.apple.com/us/app/agendue/id819949893?ls=1&amp;mt=8" target="_blank">
          <%= image_tag("home/App-Store.png", :alt => "Agendue iOS", :class =>"img-responsive inline home-download-mobile") %>
        </a>
        <a href="https://play.google.com/store/apps/details?id=com.agendue.agendue" target="_blank">
          <%= image_tag("home/Play-Store.png", :alt => "Agendue Android", :class =>"img-responsive inline home-download-mobile") %>
        </a>
      </div>
    </div>
    <div class="jumbotron home home-features">
      <h1><span class="orange">Agendue</span> is loaded with features</h1>
      <div class="row">
        <div class="col-md-3">
          <p>Create projects</p>
          <p>Track progress</p>
          <p>Share with teams</p>
        </div>
        <div class="col-md-3 visible-md-block visible-lg-block">
          <p>View a calendar</p>
          <p>Duplicate projects</p>
          <p>Take notes</p>
        </div>
        <div class="col-md-3 visible-md-block visible-lg-block">
          <p>View analytics</p>
          <p>Manage workloads</p>
          <p>Set due dates</p>
        </div>
        <div class="col-md-3">
          <p>Create tasks</p>
          <p>Leave bulletins</p>
          <p>And more...</p>
        </div>
      </div>
    </div>
    <div class="jumbotron home home-pricing">
      <h1><span class="orange">Agendue</span> is affordable</h1>
      <div class="row text-center">
        <div class="col-md-1">

        </div>
        <div class="col-md-4">
          <div class="home-pricing-card">
            <h3><span class="blue">Agendue</span></h3>
            <h5>Free forever</h5>
            <hr>
            <ul>
              <li>Unlimited tasks</li>
              <li>Unlimited projects</li>
              <li>Unlimited bulletins</li>
              <li>Unlimited whiteboards</li>
              <li>Unlimited team members</li>
            </ul>
          </div>
        </div>
        <div class="col-md-2"></div>
        <div class="col-md-4">
          <div class="home-pricing-card">
            <h3><span class="orange">Agendue for Business</span></h3>
            <h5>Priced by number of employees</h5>
            <hr>
            <ul>
              <li>All the features of Agendue</li>
              <li>Powerful analytics</li>
              <li>Project duplication</li>
              <li>Custom branding</li>
              <li>More business-centric features</li>
            </ul>
          </div>
        </div>
        <div class="col-md-1"></div>
      </div>
      <div class="row text-center">
        <p>Want to sign up for Agendue for Business? <%= link_to "Contact Us", contact_path, :class => "orange" %> and we'll work out a deal.</p>
        <p>Agendue is free for personal, student, and nonprofit organization use. Business customers must subscribe to Agendue for Business.</p>
      </div>
    </div>
    <div class="jumbotron home home-footer">
      <div class="row text-center">
        <p>
          <%= link_to "Help", helps_path %> |
          <%= link_to "Privacy Policy", privacy_path %> |
          <%= link_to "Contact Us", contact_path %> |
          &copy Fogerty Lombardo, LLC
        </p>
      </div>
    </div>
  </div>
</body>
</html>

AgendueWeb/app/views/home/home.mobile.erb
<!DOCTYPE html>
<html>
<head>
  <title>Agendue</title>
   <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-49704891-1', 'agendue.com');
      ga('send', 'pageview');

    </script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js"></script>
        <script type="text/javascript" src="/assets/jquery.fullPage.js?body=1"></script>
        <script type="text/javascript">
            $(document).ready(function() {
                $.fn.fullpage({
                    slidesColor: ['none', '#3692d5', '#3692d5', '#3692d5'],
                    // slidesColor: ['none', '#3692d5', '#3692d5', '#00c90d', '#3692d5', '#ffab25', '#3692d5'],
                    anchors: ['1', '2', '3', '4'],
                    scrollingSpeed: 600,
                    css3: true,
                });
            });
    </script>
      <meta name="viewport" content="target-densitydpi=device-dpi, initial-scale=1.0, user-scalable=no" />
      <link href='https://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <link rel="apple-touch-icon" href="/assets/agendue-icon.png" >

</head>
<body class="homepage">
    <div class="section active">
        <div class="homepageouter">
            <div class="homepagemiddle">
                <div class="homepageinner">
                    <div class="homepagefirstcontent">
                        <table class="homepagefirstcontenttable">
                            <tr class="homepagefirstcontenttable">
                                <td class="homepagefirstcontenttableimg">
                                    <%= image_tag "agendue-icon.png", :class => "homepagelogo" %>
                                </td>
                                <td class="homepagefirstcontenttable">
                                    <h2 class="homepagefirstcontent homepagelightblue">Get organized,</h2>
                                    <h2 class="homepageorange homepagefirstcontent">together.</h2>
                                    <h1 class="homepagefirstcontent">Agendue</h1>
                                </td>
                            </tr>
                        </table>
                        <div class="homepagebuttonwrapper">
                            <%= link_to "Login", login_path, :class => "homepagebutton" %>
                            <%= link_to "Sign Up", new_user_path, :class => "homepagebutton" %>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="homepage1bottomwrapper">
            <div class="homepage1bottom">
                <p class="white">Swipe to continue</p>
            </div>
        </div>
    </div>
    <div class="section">
        <div class="homepage7wrapper">
            <div class="homepageouter7">
                <table class="homepageouter7">
                    <tr>
                        <td class="homepageouter7">
                            <%= image_tag "agendue-icon.png", :class => "homepage7" %>
                        </td>
                        <td class="homepageouter7">
                                <%= link_to "Meet the Team", about_path, :class => "homepagebutton7 mobilebutton7", data: {no_turbolink: true} %>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="homepage7bottom">
                <a href="#1" class="homepageupbutton7">Click here to go to top.</a>
            </div>
            <div class="homepagefootercontainer">
                <p class="homepagefooter">&copy Fogerty Lombardo, LLC | </p>
                <%= link_to "Privacy Policy", privacy_path, :class => "homepagefooter"%> | 
                <%= link_to "Contact Us", contact_path, :class => "homepagefooter" %>

            </div>
        </div>
    </div>
</body>