AgendueWeb/config/routes.rb
Agendue::Application.routes.draw do

  resources :notifications

  get "agendue_calendar/show"
  get "agendue_calendar/ics"
  resources :personal_tasks
  get 'personal_tasks/all/complete' => 'personal_tasks#complete'
  get 'personal_tasks/all/incomplete' => 'personal_tasks#incomplete'

  resources :premium_users

  resources :devices

  resources :helps

    root 'home#home'

  get "password_resets/new"
  get 'index' => 'static#home'
  get 'users/new' =>'users#new'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get 'projects/:id/empty_wiki' => 'projects#empty_wiki'
  post 'projects/:id/removeshare' => 'projects#removeshare', as: :removeshare
  get 'projects/:id/messages' => 'projects#allmessages', as: :project_messages
  get 'projects/:id/public' => 'projects#show_public', as: :project_show_public
  get '/projects/shares' => 'projects#shares', as: :projects_shares_OLD
  get 'projects/:id/shares' => 'projects#shares', as: :project_shares
  get '/tasks/assigned' => 'tasks#assigned', as: :your_tasks
  get '/tasks/calendar' => 'agendue_calendar#show_old', as: :old_calendar
  get '/calendar' => 'agendue_calendar#show', as: :tasks_calendar
  get '/home' => 'static#home'
  get '/contact' => 'static#contact'
  get '/about' => 'static#about'
  get '/privacy' => 'static#privacy'
  get '/termsandconditions' =>'static#termsandconditions'

  get 'admin' => 'admin#index'
  get 'landing' => 'landing#index'
  get 'landing/score' => 'landing#score'
  get 'landing/personal' => 'landing#personal'
  get 'landing/incomplete_count' => 'landing#incomplete_count'
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get]
  match '/auth/failure', :to => 'sessions#failure', via: [:get]

  get 'userinfo' => 'users#show'
  get '/user' => 'users#show', as: :just_user
  get 'projects/copy' => 'projects#copy_start', as: :copystart
  get 'projects/:id/copy' => 'projects#copy_options', as: :copyname
  post 'projects/:id/copy' => 'projects#copy_run', as: :copy
  post 'messages' => 'messages#create', as: :messages
  get 'projects/:id/wiki' => 'projects#showwiki', as: :show_wiki
  get 'projects/:id/wiki/edit' => 'projects#editwiki', as: :edit_project_wiki
  post 'projects/:id/wiki/edit' => 'projects#updateprojectwiki', as: :project_wiki
  get 'projects/:id/tasks/complete' => 'projects#complete_tasks', as: :project_complete_tasks
  get 'projects/:id/tasks/incomplete' => 'projects#incomplete_tasks', as: :project_incomplete_tasks
  get 'projects/:id/tasks' => 'projects#tasks', as: :project_tasks
  get 'projects/:id/shares/canshare' => 'projects#canshare', as: :project_can_share
  get 'projects/:id/shares' => 'projects#shares'
  get 'oauthpassword' => 'sessions#oauthpassword', as: :oauthpassword
  get 'tour' => 'newusertour#tour', as: :tour
  get 'help' => 'helps#index', as: :all_help
  get 'tasks/assigned/complete' => 'tasks#assignedcomplete', as: :complete_assigned_tasks
  get 'tasks/assigned/incomplete' => 'tasks#assignedincomplete', as: :incomplete_assigned_tasks
  get 'tasks/complete' => 'tasks#allcomplete', as: :complete_tasks
  get 'tasks/incomplete' => 'tasks#allincomplete', as: :incomplete_tasks
  get 'tasks/labels' => 'tasks#labels', as: :task_labels
  get 'calendar/feed/:id/:hash' => 'agendue_calendar#ics', as: :calendar_ics
  get 'admin/addpremium' => 'admin#createpremiumoverride', as: :create_premium_override
  post 'admin/addpremium' => 'admin#addpremiumoverride', as: :add_premium_override
  get 'admin/showpremium' => 'admin#showpremiumoverride', as: :show_premium_override
  get 'charges/explainfeatures' => 'charges#explainfeatures', as: :explainfeatures
  get 'atlanta' => 'static#atlanta', as: :atlanta
  get 'acknowledgements' => 'static#acknowledgements', as: :acknowledgements

  #analytics
  get 'projects/:id/analytics' => 'analytics#index', as: :project_analytics
  get 'projects/:id/analytics/status' => 'analytics#status', as: :analytics_status
  get 'projects/:id/analytics/tasks_per_user' => 'analytics#tasks_per_user', as: :analytics_tasks_per_user
  get 'projects/:id/analytics/tasks_complete_per_user' => 'analytics#tasks_complete_per_user', as: :analytics_tasks_complete_per_user
  get 'projects/:id/analytics/percent_complete' => 'analytics#percent_complete', as: :analytics_percent_complete

  resources :admin

  resources :help

  resources :charges

  resources :users

  resources :tasks

  resources :projects

  resources :sessions

  resources :password_resets
end

AgendueWeb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Agendue</title>
   <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-49704891-1', 'agendue.com');
    ga('send', 'pageview');

  </script>
  <link href='https://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <link rel="apple-touch-icon" href="assets/agendue-icon.png" >
  <style>
    a.blue, button.blue {
      color: white;
      background-color: <%= primary_color() %>;
    }
    a.blue:hover, button.blue:hover {
      background-color: <%= tertiary_color() %>;
    }
  </style>
</head>
<body style="background-color:<%= secondary_color() %>">
  <nav class="navbar navbar-default navbar-fixed-top blue" role="navigation" style="background-color:<%= primary_color() %>">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("/assets/agendue-icon.png", :alt => "Agendue", :class => "nav-icon"), root_path, :class => "navbar-brand" %>
        <%= link_to "Agendue", root_path, :class => "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav blue">
          <% if session[:userid] %>
            <li><%= link_to "Projects", projects_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Tasks <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "All Tasks", tasks_path %></li>
                <li><%= link_to "Your Tasks", your_tasks_path %></li>
              </ul>
              <li><%= link_to "Personal Tasks", personal_tasks_path %></li>

              <li><%= link_to "Calendar", tasks_calendar_path %></li>
            </li>
          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if session[:userid] %>
            <% @user = User.find(session[:userid]) %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= @user.firstname + " " + @user.lastname %><span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Your Account", user_path(session[:userid]) %></li>
                <li class="divider"></li>
                <li><%= link_to "Help", helps_path %></li>
                <li><%= link_to "Tour", tour_path %></li>
                <li class="divider"></li>
                <% if is_admin(session[:userid]) == true %>
                  <li><%= link_to "Admin", admin_path %></li>
                  <li><%= link_to "Notifications", notifications_path %></li>
                  <li class="divider"></li>
                <% end %>
                <li><%= link_to "Log Out", logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign In", login_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <div class="container" id="body-container">
    <% if flash[:error] %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= flash[:error] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= flash[:alert] %>
      </div>
    <% elsif flash[:notice] %>
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
    <footer>
      <%= link_to "Help", helps_path %> |
      <%= link_to "Privacy Policy", privacy_path %> |
      <%= link_to "Contact Us", contact_path %> |
      <%= link_to "Acknowledgements", acknowledgements_path %> |
      &copy Fogerty Lombardo, LLC
    </footer>
  </div>

</body>
</html>

AgendueWeb/app/views/layouts/home.html.erb
<%= yield %>

AgendueWeb/app/views/layouts/home.mobile.erb
<%= yield %>

AgendueWeb/app/views/layouts/newusertour.html.erb
<%= yield %>

AgendueWeb/app/views/layouts/newusertour.mobile.erb
<%= yield %>