AgendueWeb/config/routes.rb
Agendue::Application.routes.draw do

  resources :notifications

  get "agendue_calendar/show"
  get "agendue_calendar/ics"
  resources :personal_tasks
  get 'personal_tasks/all/complete' => 'personal_tasks#complete'
  get 'personal_tasks/all/incomplete' => 'personal_tasks#incomplete'

  resources :premium_users

  resources :devices

  resources :helps

    root 'home#home'

  get "password_resets/new"
  get 'index' => 'static#home'
  get 'users/new' =>'users#new'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get 'projects/:id/empty_wiki' => 'projects#empty_wiki'
  post 'projects/:id/removeshare' => 'projects#removeshare', as: :removeshare
  get 'projects/:id/messages' => 'projects#allmessages', as: :project_messages
  get 'projects/:id/public' => 'projects#show_public', as: :project_show_public
  get '/projects/shares' => 'projects#shares', as: :projects_shares_OLD
  get 'projects/:id/shares' => 'projects#shares', as: :project_shares
  get '/tasks/assigned' => 'tasks#assigned', as: :your_tasks
  get '/tasks/calendar' => 'agendue_calendar#show_old', as: :old_calendar
  get '/calendar' => 'agendue_calendar#show', as: :tasks_calendar
  get '/home' => 'static#home'
  get '/contact' => 'static#contact'
  get '/about' => 'static#about'
  get '/privacy' => 'static#privacy'
  get '/termsandconditions' =>'static#termsandconditions'

  get 'admin' => 'admin#index'
  get 'landing' => 'landing#index'
  get 'landing/score' => 'landing#score'
  get 'landing/personal' => 'landing#personal'
  get 'landing/incomplete_count' => 'landing#incomplete_count'
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get]
  match '/auth/failure', :to => 'sessions#failure', via: [:get]

  get 'userinfo' => 'users#show'
  get '/user' => 'users#show', as: :just_user
  get 'projects/copy' => 'projects#copy_start', as: :copystart
  get 'projects/:id/copy' => 'projects#copy_options', as: :copyname
  post 'projects/:id/copy' => 'projects#copy_run', as: :copy
  post 'messages' => 'messages#create', as: :messages
  get 'projects/:id/wiki' => 'projects#showwiki', as: :show_wiki
  get 'projects/:id/wiki/edit' => 'projects#editwiki', as: :edit_project_wiki
  post 'projects/:id/wiki/edit' => 'projects#updateprojectwiki', as: :project_wiki
  get 'projects/:id/tasks/complete' => 'projects#complete_tasks', as: :project_complete_tasks
  get 'projects/:id/tasks/incomplete' => 'projects#incomplete_tasks', as: :project_incomplete_tasks
  get 'projects/:id/tasks' => 'projects#tasks', as: :project_tasks
  get 'projects/:id/shares/canshare' => 'projects#canshare', as: :project_can_share
  get 'projects/:id/shares' => 'projects#shares'
  get 'oauthpassword' => 'sessions#oauthpassword', as: :oauthpassword
  get 'tour' => 'newusertour#tour', as: :tour
  get 'help' => 'helps#index', as: :all_help
  get 'tasks/assigned/complete' => 'tasks#assignedcomplete', as: :complete_assigned_tasks
  get 'tasks/assigned/incomplete' => 'tasks#assignedincomplete', as: :incomplete_assigned_tasks
  get 'tasks/complete' => 'tasks#allcomplete', as: :complete_tasks
  get 'tasks/incomplete' => 'tasks#allincomplete', as: :incomplete_tasks
  get 'tasks/labels' => 'tasks#labels', as: :task_labels
  get 'calendar/feed/:id/:hash' => 'agendue_calendar#ics', as: :calendar_ics
  get 'admin/addpremium' => 'admin#createpremiumoverride', as: :create_premium_override
  post 'admin/addpremium' => 'admin#addpremiumoverride', as: :add_premium_override
  get 'admin/showpremium' => 'admin#showpremiumoverride', as: :show_premium_override
  get 'charges/explainfeatures' => 'charges#explainfeatures', as: :explainfeatures
  get 'atlanta' => 'static#atlanta', as: :atlanta
  get 'acknowledgements' => 'static#acknowledgements', as: :acknowledgements

  #analytics
  get 'projects/:id/analytics' => 'analytics#index', as: :project_analytics
  get 'projects/:id/analytics/status' => 'analytics#status', as: :analytics_status
  get 'projects/:id/analytics/tasks_per_user' => 'analytics#tasks_per_user', as: :analytics_tasks_per_user
  get 'projects/:id/analytics/tasks_complete_per_user' => 'analytics#tasks_complete_per_user', as: :analytics_tasks_complete_per_user
  get 'projects/:id/analytics/percent_complete' => 'analytics#percent_complete', as: :analytics_percent_complete

  resources :admin

  resources :help

  resources :charges

  resources :users

  resources :tasks

  resources :projects

  resources :sessions

  resources :password_resets
end

AgendueWeb/app/models/personal_task.rb
class PersonalTask < ActiveRecord::Base
	def name
		title
	end

	def assignedto
		user = User.find_by_id(userid)
		return user.firstname + " " + user.lastname
	end

	def projectid
		nil
	end

	def self.all_personal_tasks(id)
		@personal_tasks = PersonalTask.find(:all, :conditions => {:userid => id})
    if @personal_tasks == nil
      @personal_tasks = Array.new()
    end

		@personal_tasks = PersonalTask.sort(@personal_tasks)

	end

	def self.all_incomplete_personal_tasks(id)
		@incomplete = PersonalTask.find(:all, :conditions => {:userid => id, :complete => false })
    if @incomplete == nil
      @incomplete = Array.new()
    end

		@incomplete = PersonalTask.sort(@incomplete)

	end

	def self.all_complete_personal_tasks(id)
		@complete = PersonalTask.find(:all, :conditions => {:userid => id, :complete => true })
		if @complete == nil
			@complete = Array.new()
		end

		@complete = PersonalTask.sort(@complete)
	end

	def self.sort(tasks)
		tasks.sort do |a,b|
			case
			when a.duedate == nil
				1
			when b.duedate == nil
				-1
			else
				DateTime.parse(a.duedate.to_s + 'T00:00:00+0:00').to_i <=> DateTime.parse(b.duedate.to_s + 'T00:00:00+0:00').to_i
			end
		end
	end

	def self.labels
		arr = Array.new(['None', 'Red', 'Green', 'Blue', 'Yellow'])
    	return arr
  	end
end

AgendueWeb/app/controllers/personal_tasks_controller.rb
class PersonalTasksController < ApplicationController
  before_action :authorize, only: [:show, :edit, :update, :destroy]
  # GET /personal_tasks
  # GET /personal_tasks.json
  def index
    @personal_tasks = PersonalTask.all_personal_tasks(session[:userid])
    @complete = PersonalTask.all_complete_personal_tasks(session[:userid])
    @incomplete = PersonalTask.all_incomplete_personal_tasks(session[:userid])
  end

  def incomplete
    @incomplete = PersonalTask.all_incomplete_personal_tasks(session[:userid])
  end

  def complete
    @complete = PersonalTask.all_complete_personal_tasks(session[:userid])
  end

  # GET /personal_tasks/1
  # GET /personal_tasks/1.json
  def show
    @personal_task = PersonalTask.find(params[:id])
    if @personal_task.userid != session[:userid]
      flash[:error] = "You don't have access to that task"
      redirect_to personal_tasks_path
    end
  end

  # GET /personal_tasks/new
  def new
    @personal_task = PersonalTask.new
  end

  # GET /personal_tasks/1/edit
  def edit
    @personal_task = PersonalTask.find(params[:id])
    if @personal_task.userid != session[:userid]
      flash[:error] = "You don't have access to that task"
      redirect_to personal_tasks_path
    end
  end

  # POST /personal_tasks
  # POST /personal_tasks.json
  def create
    @personal_task = PersonalTask.new(personal_task_params)
    @personal_task.userid = session[:userid]
    if personal_task_params[:label] == nil || personal_task_params[:label] == ""
      @personal_task.label = 0
    end
    @personal_task.complete = false
    respond_to do |format|
      if @personal_task.save
        flash[:alert] = "Task created"
        format.html { redirect_to @personal_task }
        format.json { render action: 'show', status: :created, location: @personal_task }
      else
        format.html { render action: 'new' }
        format.json { render json: @personal_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personal_tasks/1
  # PATCH/PUT /personal_tasks/1.json
  def update
    @personal_task = PersonalTask.find(params[:id])
    if @personal_task.userid != session[:userid]
      flash[:error] = "You don't have access to that task"
      redirect_to personal_tasks_path
    else
      respond_to do |format|
        if @personal_task.update(personal_task_params)
          flash[:alert] = "Task saved"
          format.html { redirect_to personal_tasks_path}
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @personal_task.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /personal_tasks/1
  # DELETE /personal_tasks/1.json
  def destroy
    set_personal_task
    if @personal_task.userid != session[:userid]
      flash[:error] = "You don't have access to that task"
      redirect_to personal_tasks_path
    else
      @personal_task.destroy
      respond_to do |format|
        flash[:alert] = "Task deleted"
        format.html { redirect_to personal_tasks_url }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personal_task
      @personal_task = PersonalTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personal_task_params
      params.require(:personal_task).permit(:title, :label, :description, :complete, :userid, :duedate)
    end
end

AgendueWeb/app/helpers/personal_tasks_helper.rb
module PersonalTasksHelper
end

AgendueWeb/app/views/personal_tasks/_form.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <%= form_for(@personal_task) do |f| %>
      <div class="input-group">
        <span class="input-group-addon">Title</span>
        <%= f.text_field :title, :autocomplete => "off", :class => "form-control" %>
      </div>
      <br>
      <div class="input-group">
        <span class="input-group-addon">Description</span>
        <%= f.text_area :description, :rows => 3, :class => "form-control", :autocomplete => "off" %>
      </div>
      <br>
      <div class="input-group">
        <span class="input-group-addon">Due Date</span>
        <%= f.text_field :duedate, :class => "form-control", :id => "task_duedate" %>
      </div>
      <br>
      <div class="input-group">
        <%= f.label "Label" %><br>
        <%= f.select :label, PersonalTask.labels.collect {|v,i| [v,PersonalTask.labels.index(v)]}, {:selected => @personal_task.label}, {:class => "form-control"}%>
      </div> 
      <br>
      <div class="input-group">
        <%= button_to task_path(@personal_task), :method => :post, :class => "btn btn-default blue"  do %>
          <span class="glyphicon glyphicon-floppy-disk"></span> Save Task
        <% end %><br>
      </div>
    <% end %>

    <%= button_to 'Remove Task', @personal_task, method: :delete, :class => "btn btn-default red", data: { confirm: 'Are you sure you want to permanently delete this task?' } %>
  </div>
  </div>
</div>
<script>
$(function() {
    $("#task_duedate").datepicker({ dateFormat: "yy-mm-dd" });
});
</script>

AgendueWeb/app/views/personal_tasks/edit.html.erb
<div class="page-header">
  <h1>Editing Task <%= @personal_task.name %></h1>
</div>
<div class="panel panel-default">
  <div class="panel-body">
    <%= form_for(@personal_task) do |f| %>
      <div class="input-group">
        <span class="input-group-addon">Title</span>
        <%= f.text_field :title, :autocomplete => "off", :class => "form-control" %>
      </div>
      <br>
      <div class="input-group">
        <span class="input-group-addon">Description</span>
        <%= f.text_area :description, :rows => 3, :class => "form-control", :autocomplete => "off" %>
      </div>
      <br>
      <div class="input-group">
        <span class="input-group-addon">Due Date</span>
        <%= f.text_field :duedate, :class => "form-control", :id => "task_duedate" %>
      </div>
      <br>
      <div class="input-group">
        <%= f.label "Label" %><br>
        <%= f.select :label, PersonalTask.labels.collect {|v,i| [v,PersonalTask.labels.index(v)]}, {:selected => @personal_task.label}, {:class => "form-control"}%>
      </div> 
      <br>
      <div class="input-group">
        <%= button_to task_path(@personal_task), :method => :post, :class => "btn btn-default blue"  do %>
          <span class="glyphicon glyphicon-floppy-disk"></span> Save Task
        <% end %><br>
      </div>
    <% end %>

    <%= button_to 'Remove Task', @personal_task, method: :delete, :class => "btn btn-default red", data: { confirm: 'Are you sure you want to permanently delete this task?' } %>
  </div>
  </div>
</div>
<script>
$(function() {
    $("#task_duedate").datepicker({ dateFormat: "yy-mm-dd" });
});
</script>

AgendueWeb/app/views/personal_tasks/index.html.erb
<div class="page-header">
  <h1>Personal Tasks</h1>
</div>
<%= button_to new_personal_task_path, :method => :get, :class => "btn btn-default green"  do %>
  <span class="glyphicon glyphicon-plus"></span> New Task
<% end %><br>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#incomplete">Incomplete Tasks</a></h3>
  </div>
  <div id="incomplete" class="panel-collapse collapse in">
    <div class="panel-body">
      <% if @incomplete.count > 0 %>
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <td></td>
                <td>Task Title</td>
                <td>Due Date</td>
                <td>Assigned To</td>
                <td>Label</td>
              </tr>
            </thead>
            <tbody>
              <% @incomplete.each do |task| %>
              <tr>
                <td>
                    <%= form_for(task) do |f| %>
                      <%= f.hidden_field :complete, :value => '1' %>
                      <%= f.submit raw('&#9744;'), :class => "completebutton" %>
                    <% end %>
                </td>
                <td><%= link_to sanitize(task.name), personal_task_path(task) %></td>
                <% if task.duedate %>
                  <td class="content"><p><%= task.duedate.to_date %></p></td>
                <% else %>
                  <td></td>
                <% end %>
                <td><%= task.assignedto %></td>
                <td>
                  <% if task.label && task.label != 0 %>
                    <div style="border: 1px solid <%=Task.labels[task.label].downcase %>;border-radius:5px;width:40px;height:40px;background-color:<%= Task.labels[task.label].downcase %>"></div>
                  <% end %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% else %>
        There are no incomplete tasks.
      <% end %>
    </div>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#complete">Complete Tasks</a></h3>
  </div>
  <div id="complete" class="panel-collapse collapse in">
    <div class="panel-body">
      <% if @complete.count > 0 %>
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <td></td>
                <td>Task Title</td>
                <td>Due Date</td>
                <td>Assigned To</td>
                <td>Label</td>
              </tr>
            </thead>
            <tbody>
              <% @complete.each do |task| %>
              <tr>
                <td>
                    <%= form_for(task) do |f| %>
                      <%= f.hidden_field :complete, :value => '0' %>
                      <%= f.submit raw('&#9745;'), :class => "completebutton" %>
                    <% end %>
                </td>
                <td><%= link_to sanitize(task.name), personal_task_path(task) %></td>
                <% if task.duedate %>
                  <td class="content"><p><%= task.duedate.to_date %></p></td>
                <% else %>
                  <td></td>
                <% end %>
                <td><%= task.assignedto %></td>
                <td>
                  <% if task.label && task.label != 0 %>
                    <div style="border: 1px solid <%=Task.labels[task.label].downcase %>;border-radius:5px;width:40px;height:40px;background-color:<%= Task.labels[task.label].downcase %>"></div>
                  <% end %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% else %>
        There are no complete tasks.
      <% end %>
    </div>
  </div>
</div>

AgendueWeb/app/views/personal_tasks/new.html.erb
<div class="page-header">
  <h1>New Task</h1>
</div>
<div class="panel panel-default">
  <div class="panel-body">
    <%= form_for(@personal_task) do |f| %>
      <div class="input-group">
        <span class="input-group-addon">Title</span>
        <%= f.text_field :title, :autocomplete => "off", :class => "form-control" %>
      </div>
      <br>
      <div class="input-group">
        <span class="input-group-addon">Description</span>
        <%= f.text_area :description, :rows => 3, :class => "form-control", :autocomplete => "off" %>
      </div>
      <br>
      <div class="input-group">
        <span class="input-group-addon">Due Date</span>
        <%= f.text_field :duedate, :class => "form-control", :id => "task_duedate" %>
      </div>
      <br>
      <div class="input-group">
        <%= f.label "Label" %><br>
        <%= f.select :label, PersonalTask.labels.collect {|v,i| [v,PersonalTask.labels.index(v)]}, {:selected => @personal_task.label}, {:class => "form-control"}%>
      </div> 
      <br>
      <div class="input-group">
        <%= button_to task_path(@personal_task), :method => :post, :class => "btn btn-default blue"  do %>
          <span class="glyphicon glyphicon-floppy-disk"></span> Save Task
        <% end %><br>
      </div>
    <% end %>

    <%= button_to 'Cancel', personal_tasks_path, method: :get, :class => "btn btn-default red" %>
  </div>
  </div>
</div>
<script>
$(function() {
    $("#task_duedate").datepicker({ dateFormat: "yy-mm-dd" });
});
</script>

AgendueWeb/app/views/personal_tasks/show.html.erb
<div class="page-header">
  <h1><%= @personal_task.name %></h1>
</div>

<div class="list-group">
    <% if @personal_task.label && @personal_task.label != 0 %>
    <div class="list-group-item">
      <div style="border: 1px solid <%=PersonalTask.labels[@personal_task.label].downcase %>;border-radius:5px;width:40px;height:40px;background-color:<%= PersonalTask.labels[@personal_task.label].downcase %>"></div>
    </div>
    <% end %>
    <% if @personal_task.description && @personal_task.description.length > 0%>
      <div class="list-group-item">
        <p>
          <strong>Description: </strong>
          <%= @personal_task.description %>
        </p>
      </div>
    <% end %>
    <% if @personal_task.duedate %>
      <div class="list-group-item">
        <p>
          <strong>Due Date: </strong>
          <%= @personal_task.duedate.to_date %>
        </p>
      </div>
    <% end %>
    <div class="list-group-item">
      <p>
        <% if @personal_task.complete == true %>
          <strong>Completed</strong>
        <% else %>
          <strong>Incomplete</strong>
        <% end %>
      </p>
    </div>
</div>

<% if @personal_task.complete == true %>
  <%= form_for(@personal_task) do |f| %>
    <%= f.hidden_field :complete, :value => '0' %>
    <%= button_to personal_task_path(@personal_task), :method => :post, :class => "btn btn-default green"  do %>
      <span class="glyphicon glyphicon-unchecked"></span> Mark Incomplete
    <% end %>
  <% end %>
<% else %>
  <%= form_for(@personal_task) do |f| %>
    <%= f.hidden_field :complete, :value => '1' %>
    <%= button_to personal_task_path(@personal_task), :method => :post, :class => "btn btn-default green"  do %>
      <span class="glyphicon glyphicon-ok"></span> Mark Complete
    <% end %>
  <% end %>
<% end %><br>
<%= button_to edit_personal_task_path(@personal_task), :method => :get, :class => "btn btn-default blue"  do %>
  <span class="glyphicon glyphicon-pencil"></span> Edit Task
<% end %><br>
<%= button_to 'Remove Task', @personal_task, method: :delete, :class => "btn btn-default red", data: { confirm: 'Are you sure you want to permanently delete this task?' } %>