AgendueWeb/config/routes.rb
Agendue::Application.routes.draw do

  resources :notifications

  get "agendue_calendar/show"
  get "agendue_calendar/ics"
  resources :personal_tasks
  get 'personal_tasks/all/complete' => 'personal_tasks#complete'
  get 'personal_tasks/all/incomplete' => 'personal_tasks#incomplete'

  resources :premium_users

  resources :devices

  resources :helps

    root 'home#home'

  get "password_resets/new"
  get 'index' => 'static#home'
  get 'users/new' =>'users#new'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get 'projects/:id/empty_wiki' => 'projects#empty_wiki'
  post 'projects/:id/removeshare' => 'projects#removeshare', as: :removeshare
  get 'projects/:id/messages' => 'projects#allmessages', as: :project_messages
  get 'projects/:id/public' => 'projects#show_public', as: :project_show_public
  get '/projects/shares' => 'projects#shares', as: :projects_shares_OLD
  get 'projects/:id/shares' => 'projects#shares', as: :project_shares
  get '/tasks/assigned' => 'tasks#assigned', as: :your_tasks
  get '/tasks/calendar' => 'agendue_calendar#show_old', as: :old_calendar
  get '/calendar' => 'agendue_calendar#show', as: :tasks_calendar
  get '/home' => 'static#home'
  get '/contact' => 'static#contact'
  get '/about' => 'static#about'
  get '/privacy' => 'static#privacy'
  get '/termsandconditions' =>'static#termsandconditions'

  get 'admin' => 'admin#index'
  get 'landing' => 'landing#index'
  get 'landing/score' => 'landing#score'
  get 'landing/personal' => 'landing#personal'
  get 'landing/incomplete_count' => 'landing#incomplete_count'
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get]
  match '/auth/failure', :to => 'sessions#failure', via: [:get]

  get 'userinfo' => 'users#show'
  get '/user' => 'users#show', as: :just_user
  get 'projects/copy' => 'projects#copy_start', as: :copystart
  get 'projects/:id/copy' => 'projects#copy_options', as: :copyname
  post 'projects/:id/copy' => 'projects#copy_run', as: :copy
  post 'messages' => 'messages#create', as: :messages
  get 'projects/:id/wiki' => 'projects#showwiki', as: :show_wiki
  get 'projects/:id/wiki/edit' => 'projects#editwiki', as: :edit_project_wiki
  post 'projects/:id/wiki/edit' => 'projects#updateprojectwiki', as: :project_wiki
  get 'projects/:id/tasks/complete' => 'projects#complete_tasks', as: :project_complete_tasks
  get 'projects/:id/tasks/incomplete' => 'projects#incomplete_tasks', as: :project_incomplete_tasks
  get 'projects/:id/tasks' => 'projects#tasks', as: :project_tasks
  get 'projects/:id/shares/canshare' => 'projects#canshare', as: :project_can_share
  get 'projects/:id/shares' => 'projects#shares'
  get 'oauthpassword' => 'sessions#oauthpassword', as: :oauthpassword
  get 'tour' => 'newusertour#tour', as: :tour
  get 'help' => 'helps#index', as: :all_help
  get 'tasks/assigned/complete' => 'tasks#assignedcomplete', as: :complete_assigned_tasks
  get 'tasks/assigned/incomplete' => 'tasks#assignedincomplete', as: :incomplete_assigned_tasks
  get 'tasks/complete' => 'tasks#allcomplete', as: :complete_tasks
  get 'tasks/incomplete' => 'tasks#allincomplete', as: :incomplete_tasks
  get 'tasks/labels' => 'tasks#labels', as: :task_labels
  get 'calendar/feed/:id/:hash' => 'agendue_calendar#ics', as: :calendar_ics
  get 'admin/addpremium' => 'admin#createpremiumoverride', as: :create_premium_override
  post 'admin/addpremium' => 'admin#addpremiumoverride', as: :add_premium_override
  get 'admin/showpremium' => 'admin#showpremiumoverride', as: :show_premium_override
  get 'charges/explainfeatures' => 'charges#explainfeatures', as: :explainfeatures
  get 'atlanta' => 'static#atlanta', as: :atlanta
  get 'acknowledgements' => 'static#acknowledgements', as: :acknowledgements

  #analytics
  get 'projects/:id/analytics' => 'analytics#index', as: :project_analytics
  get 'projects/:id/analytics/status' => 'analytics#status', as: :analytics_status
  get 'projects/:id/analytics/tasks_per_user' => 'analytics#tasks_per_user', as: :analytics_tasks_per_user
  get 'projects/:id/analytics/tasks_complete_per_user' => 'analytics#tasks_complete_per_user', as: :analytics_tasks_complete_per_user
  get 'projects/:id/analytics/percent_complete' => 'analytics#percent_complete', as: :analytics_percent_complete

  resources :admin

  resources :help

  resources :charges

  resources :users

  resources :tasks

  resources :projects

  resources :sessions

  resources :password_resets
end

AgendueWeb/app/models/project.rb
class Project < ActiveRecord::Base
  validates	:name, presence: true
  def self.workers_for_project(id)
    @workers = Array.new()
    project = Project.find_by_id(id)
    for shared in project.allshares.split(',')
      tempuser = User.find_by_id(shared)
      if tempuser
        @workers << tempuser
      end
    end
    @workers.sort! { |a, b| (a.firstname + " " + a.lastname).downcase <=> (b.firstname + " " + b.lastname).downcase }
  end

  def self.tasks_for_project(id)
    @tasks = Array.new
    for task in Task.where(projectid: id).load
    	@tasks << task
    end
    @tasks.sort do |a,b|
    	case
    	when a.duedate == nil
    		1
    	when b.duedate == nil
    		-1
    	else
    		DateTime.parse(a.duedate.to_s + 'T00:00:00+0:00').to_i <=> DateTime.parse(b.duedate.to_s + 'T00:00:00+0:00').to_i
    	end
    end
  end

  def self.incomplete_tasks_for_project(id)
  	tasks = Project.tasks_for_project(id)
  	@incomplete = Array.new
  	for task in tasks
  		if task.complete == nil || task.complete == false
  			@incomplete << task
  		end
  	end
  	@incomplete
  end

  def self.complete_tasks_for_project(id)
  	tasks = Project.tasks_for_project(id)
  	@complete = Array.new
  	for task in tasks
  		if task.complete == true
  			@complete << task
  		end
  	end
  	@complete
  end

  def self.projects_for_user(id)
    @projects = Array.new()
    if User.find_by_id(id).projectids != nil
      pids = User.find_by_id(id).projectids.split(",")
      for pid in pids
        project = Project.find_by_id(pid)
        if project
          @projects << project
        end
      end
    end
    @projects.sort! { |a,b| a.name.downcase <=> b.name.downcase }
  end
end

AgendueWeb/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_filter :authorize
  skip_before_filter :authorize, :only => [:show_public, :show]
  protect_from_forgery :except => [:destroy]
  before_filter :premium, :only => [:copy_options, :copy_start, :copy_run, :analytics]
  before_filter :has_access_to_project, :except => [:new, :index, :show, :show_public, :create, :copy_start]
  # GET /projects
  # GET /projects.json
  def index
    @user = User.find_by_id(session[:userid])
    @projects =  current_user_projects
    respond_to do |format|
      format.html # index.html.erb
      format.json
    end
  end

  def shares
    @project = nil
    if params[:id]
      @project = Project.find_by_id(params[:id])
    else
      @project = Project.find_by_id(session[:lastproj])
    end
    @user = User.find_by_id(session[:userid])
    @workers = Project.workers_for_project(@project.id)

  end

  def canshare
    #DEPRECATED
  end
  # GET /projects/1
  # GET /projects/1.json
  def show
    tempproject = Project.find(params[:id])
    user = User.find_by_id(session[:userid])
    if !user
      if tempproject.public == true
        redirect_to project_show_public_path(params[:id])
      else
        redirect_to login_path
      end
    else
      pids = user.projectids.split(",");
      session[:lastproj] = params[:id]

      if pids.include? String(tempproject.id)
        @project = tempproject
        @complete = Project.complete_tasks_for_project(@project.id)
        @incomplete = Project.incomplete_tasks_for_project(@project.id)

        #gathering users
        @workers = Project.workers_for_project(@project.id)

        #gathering overall completion
        if (@incomplete.size + @complete.size) == 0
          @percentdone = 0
        else
          @percentdone = @complete.size*100 / (@complete.size + @incomplete.size)
        end
        #sorting tasks
        @tasks = Project.tasks_for_project(@project.id)

        #gathering messages
        @messages = Message.where(projectid: @project.id).order(created_at: :desc)




        respond_to do |format|
          format.html # show.html.erb
          format.mobile
          format.json { render json: @tasks }
        end
      else
        if tempproject.public == true
          redirect_to project_show_public_path(params[:id])
        else
          redirect_to projects_url
        end
      end
    end

  end

  def show_public
    @project = Project.find_by_id(params[:id])
    if !@project.public
      redirect_to root_path
    else
      @complete = Project.complete_tasks_for_project(@project.id)
      @incomplete = Project.incomplete_tasks_for_project(@project.id)
    end
  end

  def complete_tasks
    pids = User.find_by_id(session[:userid]).projectids.split(",");
    tempproject = Project.find(params[:id])
    session[:lastproj] = params[:id]
    if pids.include? String(tempproject.id)
      @project = tempproject
      @complete = Project.complete_tasks_for_project(@project.id)
    end
  end

  def incomplete_tasks
    pids = User.find_by_id(session[:userid]).projectids.split(",");
    tempproject = Project.find(params[:id])
    session[:lastproj] = params[:id]
    if pids.include? String(tempproject.id)
      @project = tempproject
      @incomplete = Project.incomplete_tasks_for_project(@project.id)
    end
  end

  def tasks
    pids = User.find_by_id(session[:userid]).projectids.split(",");
    tempproject = Project.find(params[:id])
    session[:lastproj] = params[:id]
    if pids.include? String(tempproject.id)
      @project = tempproject
      @tasks = Project.tasks_for_project(@project.id)
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project.shares = ""
    @project.save!
    @is_muted = User.is_project_muted(session[:userid], @project.id)
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    user = User.find_by_id(session[:userid])
    @project.allshares = user.id
    respond_to do |format|
      if @project.save
        user.projectids += "," + String(@project.id)
        user.save!
        if project_params[:shares] == ""

        else
          share_params = {
            :proj => @project.id,
            :shares => project_params[:shares]
          }
          share (share_params)
        end
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.mobile { redirect_to @project }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.mobile { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def removeshare
    @project = Project.find_by_id(params[:id])
    @removeUser = User.find_by_id(params[:user])
    if @project && @removeUser
      shares = @project.allshares.split(",")
      newshares = ""
      shares.each do |shr|
        if shr != @removeUser.id.to_s
          newshares += shr + ","
        end
      end
      @project.update_column(:allshares, newshares)
      projects = @removeUser.projectids.split(',')
      newprojects = ''
      projects.each do |prj|
        if prj != @project.id.to_s
          newprojects += prj + ','
        end
      end
      @removeUser.update_column(:projectids, newprojects)

      for task in Task.where("assignedto = ?", (@removeUser.firstname + " " + @removeUser.lastname))
        if task.projectid == @project.projectid
          task.update_column(:assignedto, 'None')
        end
      end
    end
    redirect_to request.referrer, notice: "Team Members were successfully updated."
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    shares = @project.allshares.split(",")
    originalshares = @project.allshares
    found = false
    for share in shares
      olduser = User.find_by_id(share)
      if olduser
        if olduser.name
          if String(olduser.name).downcase == String(project_params[:shares]).downcase
            found = true
          end
        end
      end
    end

    puts 'xxxxxxxxxxxxxxx'
    puts params[:unsubscribe]
    #deal with muting project
    if params[:unsubscribe] == 'on'
      User.mute_project(session[:userid], @project.id)
      puts 'muting project'
    else
      User.unmute_project(session[:userid], @project.id)
    end

    respond_to do |format|
      if @project.update(project_params)
        if project_params[:shares] && project_params[:shares] != ""
          if found == false && project_params[:shares]
            pid = session[:lastproj]
            share_params = {
              :proj => pid,
              :shares => project_params[:shares],
              :project => @project.name,
              :morethan5 => false
            }
            @workers = Project.workers_for_project(@project.id)

            share(share_params)
            @project.save!
          else
            @project.allshares = originalshares
            @project.save!
          end
        end
        if URI(request.referrer).path == project_shares_path(@project.id)
          format.html { redirect_to project_shares_path(@project.id), notice: 'Project was successfully updated.' }
          format.mobile { redirect_to project_shares_path(@project.id) }
          format.json { head :no_content }
        else
          format.html { redirect_to @project, notice: 'Project was successfully updated.' }
          format.mobile { redirect_to @project }
          format.json { head :no_content }
        end
      else
        format.html { render action: 'edit' }
        format.mobile { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find_by_id(params[:id])
    @removeUser = User.find_by_id(session[:userid])
    if @project && @removeUser
      shares = @project.allshares.split(",")
      newshares = ""
      shares.each do |shr|
        if shr != @removeUser.id.to_s
          newshares += shr + ","
        end
      end
      @project.update_column(:allshares, newshares)
      projects = @removeUser.projectids.split(',')
      newprojects = ''
      projects.each do |prj|
        if prj != @project.id.to_s
          newprojects += prj + ','
        end
      end
      @removeUser.update_column(:projectids, newprojects)

      for task in Task.where("assignedto = ?", (@removeUser.firstname + " " + @removeUser.lastname))
        if task.projectid == @project.projectid
          task.update_column(:assignedto, 'None')
        end
      end
    end

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.mobile { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  def share (shared_params)
    user = User.find_by_name(shared_params[:shares])
    if shared_params[:shares] != "" && user
      pids = user.projectids.split(",")
      found = false
      for pid in pids
        if pid == String(shared_params[:proj])
          found = true
        end
      end
      project = Project.find_by_id(shared_params[:proj])

      if found == false
        user.projectids = user.projectids + "," + String(shared_params[:proj])
        user.save!
      end

      message = "The project " + project.name + " has been shared with you on Agendue."
      subject = project.name + " has been shared with you"
      Notification.send_notifications_to_user(subject, message, project.id, user.id)


      project.allshares = project.allshares + "," + String(user.id)
        project.save!
    else
      Thread.new do

AgendueWeb/app/helpers/projects_helper.rb
module ProjectsHelper
end

AgendueWeb/app/views/projects/copy_start.html.erb
<div class="page-header">
  <h1>Choose a Project</h1>
</div>

<div class="list-group">
	<% if @projects.count > 0 %>
		<% @projects.each do |project| %>
		<li class="list-group-item">
		    <%= link_to project.name, copyname_path(project) %>
		</li>
		<% end %>
	<% else %>
		<p>To get started, please <%= link_to "create a project", new_project_path %>.</p>
	<% end %>
</div>

AgendueWeb/app/views/projects/index.html.erb
<div class="page-header">
  <h1>Your Projects</h1>
</div>

<%= link_to new_project_path, :method => :get, :class => "btn btn-default green inline"  do %>
	<span class="glyphicon glyphicon-plus"></span> New Project
<% end %>
<%= link_to copystart_path, :method => :get, :type => "button", :class => "btn btn-default blue inline"  do %>
  <span class="glyphicon glyphicon-share"></span> Copy Project
<% end %><br><br>
<div class="list-group">
	<% if @projects.count > 0 %>
		<% @projects.each do |project| %>
		<li class="list-group-item">
		    <span class="badge">
		    	<%= link_to project, method: :delete, data: { confirm: 'Are you sure you want to remove this from your projects? Other users with access to this project will still be able to use it.' }, :class => "white" do %>
		    		<span class="glyphicon glyphicon-trash"></span>
		    	<% end %>
		    </span>
		    <%= link_to project.name, project %>
		</li>
		<% end %>
	<% else %>
		<p>To get started, please <%= link_to "create a project", new_project_path %>.</p>
	<% end %>
</div>

AgendueWeb/app/views/projects/show.html.erb
<div class="page-header">
  <h1><%= @project.name %></h1>
</div>
<%= link_to new_task_path, :method => :get, :type => "button", :class => "btn btn-default green"  do %>
  <span class="glyphicon glyphicon-plus"></span> New Task
<% end %>
<%= link_to project_analytics_path(@project), :method => :get, :type => "button", :class => "btn btn-default blue"  do %>
  <span class="glyphicon glyphicon-stats"></span> Analytics
<% end %>
<%= link_to edit_project_path(@project), :method => :get, :type => "button", :class => "btn btn-default blue"  do %>
  <span class="glyphicon glyphicon-pencil"></span> Edit Project
<% end %>
<%= link_to copyname_path(@project), :method => :get, :type => "button", :class => "btn btn-default blue"  do %>
  <span class="glyphicon glyphicon-share"></span> Copy Project
<% end %>
<br>
<% if @project.public == true %>
  <br>
  <p>Public Link: <%= link_to project_show_public_url(@project.id), project_show_public_url(@project.id) %></p>
<% end %>
<br>
<ul class="nav nav-tabs" role="tablist">
  <li class="active"><a href="#home" role="tab" data-toggle="tab"><span class="glyphicon icon-home"></span>  Home</a></li>
  <li><a href="#tasks" role="tab" data-toggle="tab"><span class="glyphicon icon-task"></span>  Tasks</a></li>
  <li><a href="#notebook" role="tab" data-toggle="tab"><span class="glyphicon icon-notebook"></span>  Notebook</a></li>
  <li><a href="#bulletins" role="tab" data-toggle="tab"><span class="glyphicon icon-pin"></span>  Bulletins</a></li>
  <li><a href="#team" role="tab" data-toggle="tab"><span class="glyphicon icon-team"></span>  Team</a></li>
</ul>

<div class="tab-content">
  <div class="tab-pane fade in active" id="home">
    <% if @incomplete.length == 0 && @complete.length == 0 %>
      <% if @wiki == nil && @messages.length == 0 %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Get Started</h3>
          </div>
          <div class="panel-body">
            <p>Get started with your new project</p>
            <ul>
              <li><%= link_to "Create a Task", new_task_path %></li>
              <li><%= link_to "Add to the Notebook",edit_project_wiki_path(@project.id) %></li>
              <li><%= link_to "Manage Team", project_shares_path(@project.id) %></li>
            </ul>
          </div>
        </div>
      <% else %>
        <h3>There are no tasks in this project.</h3>
        <p><%= link_to "Create a Task", new_task_path %></p>
      <% end %>
    <% else %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Upcoming Tasks</h3>
        </div>
        <div class="panel-body">
          <% if @incomplete.count > 0 %>
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <td></td>
                    <td>Title</td>
                    <td>Due Date</td>
                    <td>Assigned To</td>
                    <td>Label</td>
                  </tr>
                </thead>
                <tbody>
                  <% @incomplete.first(5).each do |task| %>
                  <tr>
                    <td>
                        <%= form_for(task) do |f| %>
                          <%= f.hidden_field :complete, :value => '1' %>
                          <%= f.submit raw('&#9744;'), :class => "completebutton" %>
                        <% end %>
                    </td>
                    <td><%= link_to sanitize(task.name), task_path(task) %></td>
                    <% if task.duedate %>
                      <td class="content"><p><%= task.duedate %></p></td>
                    <% else %>
                      <td></td>
                    <% end %>
                    <td><%= task.assignedto %></td>
                    <td>
                      <% if task.label && task.label != 0 %>
                        <div style="border: 1px solid <%=Task.labels[task.label].downcase %>;border-radius:5px;width:40px;height:40px;background-color:<%= Task.labels[task.label].downcase %>"></div>
                      <% end %>
                    </td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          <% else %>
            There are no upcoming tasks.
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="tab-pane fade" id="tasks">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Incomplete Tasks</h3>
      </div>
      <div class="panel-body">
        <% if @incomplete.count > 0 %>
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <td></td>
                  <td>Title</td>
                  <td>Due Date</td>
                  <td>Assigned To</td>
                  <td>Project</td>
                  <td>Label</td>
                </tr>
              </thead>
              <tbody>
                <% @incomplete.each do |task| %>
                <tr>
                  <td>
                      <%= form_for(task) do |f| %>
                        <%= f.hidden_field :complete, :value => '1' %>
                        <%= f.submit raw('&#9744;'), :class => "completebutton" %>
                      <% end %>
                  </td>
                  <td><%= link_to sanitize(task.name), task_path(task) %></td>
                  <% if task.duedate %>
                    <td class="content"><p><%= task.duedate %></p></td>
                  <% else %>
                    <td></td>
                  <% end %>
                  <td><%= task.assignedto %></td>
                  <td><%= link_to Project.find_by_id(task.projectid).name, project_path(Project.find_by_id(task.projectid)) %></td>
                  <td>
                    <% if task.label && task.label != 0 %>
                      <div style="border: 1px solid <%=Task.labels[task.label].downcase %>;border-radius:5px;width:40px;height:40px;background-color:<%= Task.labels[task.label].downcase %>"></div>
                    <% end %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        <% else %>
          There are no incomplete tasks.
        <% end %>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Complete Tasks</h3>
      </div>
      <div class="panel-body">
        <% if @complete.count > 0 %>
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <td></td>
                  <td>Title</td>
                  <td>Due Date</td>
                  <td>Assigned To</td>
                  <td>Project</td>
                  <td>Label</td>
                </tr>
              </thead>
              <tbody>
                <% @complete.each do |task| %>
                <tr>
                  <td>
                      <%= form_for(task) do |f| %>
                        <%= f.hidden_field :complete, :value => '0' %>
                        <%= f.submit raw('&#9745;'), :class => "completebutton" %>
                      <% end %>
                  </td>
                  <td><%= link_to sanitize(task.name), task_path(task) %></td>
                  <% if task.duedate %>
                    <td class="content"><p><%= task.duedate %></p></td>
                  <% else %>
                    <td></td>
                  <% end %>
                  <td><%= task.assignedto %></td>
                  <td><%= link_to Project.find_by_id(task.projectid).name, project_path(Project.find_by_id(task.projectid)) %></td>
                  <td>
                    <% if task.label && task.label != 0 %>
                      <div style="border: 1px solid <%=Task.labels[task.label].downcase %>;border-radius:5px;width:40px;height:40px;background-color:<%= Task.labels[task.label].downcase %>"></div>
                    <% end %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        <% else %>
          There are no complete tasks.
        <% end %>
      </div>
    </div>
  </div>
  <div class="tab-pane fade" id="notebook">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Notebook</h3>
      </div>
      <div class="panel-body">
        <% if @project.wiki && @project.wiki.strip.length > 0 %>
          <%= @project.wiki.html_safe %>
        <% else %>
          <p>Your notebook is empty. <%= link_to "Edit", edit_project_wiki_path(@project.id) %> it to get started.</p>
        <% end %>
      </div>
    </div>
    <%= link_to edit_project_wiki_path(@project), :method => :get, :type => "button", :class => "btn btn-default blue", :data => {no_turbolink: true }  do %>
      <span class="glyphicon glyphicon-pencil"></span> Edit Notebook
    <% end %>
  </div>
  <div class="tab-pane fade" id="bulletins">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Bulletins</h3>
      </div>
      <div class="panel-body">
        <%= form_for Message.new, :url => messages_path, :html => {:method => :post} do |f| %>
            <div class="input-group">
              <span class="input-group-addon">Message</span>
              <%= f.text_area :content, :rows => 3, :class => "form-control", :autocomplete => "off" %>
            </div>
            <br>
            <div class="input-group">
              <%= button_to messages_path, :method => :post, :class => "btn btn-default blue"  do %>
                <span class="glyphicon icon-pin-white"></span> Post
              <% end %><br>
            </div>
          <% end %>
          <% if @messages.length == 0 %>
            <p>There's nothing here. Make a bulletin board post to get started.</p>
          <% else %>
            <ul class="list-group">
              <% @messages.each do |msg| %>
              <li class="list-group-item">
                <% user = User.find_by_id(msg.user) %>
                <table class="message">
                  <tr>
                    <td class="messagepic">
                      <% if user.facebook %>
                       <%= image_tag "https://graph.facebook.com/#{user.facebook}/picture" %>
                      <% elsif user.google_picture %>
                        <%= image_tag user.google_picture %>
                      <% end %>
                    </td>
                    <td class="messagetext">
                      <p><%= user.firstname + ' ' + user.lastname %></p>
                      <p><%= msg.created_at.strftime('%Y-%m-%d') %></p>
                      <p><%= msg.content %></p>
                    </td>
                  </tr>
                </table>
              </li>
              <% end %>
            </ul>
          <% end %>
      </div>
    </div>
  </div>
  <div class="tab-pane fade" id="team">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Team</h3>
      </div>
      <div class="panel-body">
        <%= button_to project_shares_path(@project.id), :method => :get, :class => "btn btn-default blue"  do %>
          <span class="glyphicon glyphicon-cog"></span> Manage Team
        <% end %><br>
        <div class="table-responsive">
          <table class="table">
          <% @workers.each do |person| %>
            <tr>
              <td class="facebookimg">
                <% if person.facebook %>
                 <%= image_tag "https://graph.facebook.com/#{person.facebook}/picture" %>
                <% elsif person.google_picture %>
                  <%= image_tag person.google_picture %>
                <% end %>
              </td>
              <td>
                <%= sanitize(person.firstname + " " + person.lastname) %>
              </td>
            </tr>
          <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>